import { Nunito } from "next/font/google";
import "./globals.css";
import  { Toaster } from 'react-hot-toast';

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
      <Toaster />
        {children}
      </body>
    </html>
  );
}
